config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#home'
  resources :articles
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
# frozen_string_literal: true

class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: { minimum: 3, maximum: 255 }
  validates :description, presence: true, length: { minimum: 3, maximum: 255 }
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord 
    belongs_to :article
    belongs_to :category
end   

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :article_categories
  has_many :article, through: :article_categories
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  before_save { self.email = email.downcase }
  has_many :articles, dependent: :destroy
  validates :username, presence: true,
                       uniqueness: { case_sensitive: false },
                       length: { minimum: 3, maximum: 25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates :email, presence: true,
                    uniqueness: { case_sensitive: false },
                    length: { maximum: 105 },
                    format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# Application controller to handle session
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def required_user
    unless logged_in?
      flash[:alert] = 'You need to login to perform this action!!'
      redirect_to login_path
    end
  end

end

app/controllers/articles_controller.rb
# frozen_string_literal: true

# article controller
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[show edit update destroy]
  before_action :required_user, except: %i[show index]
  before_action :required_same_user, only: %i[edit destroy update]

  def show; end

  def index
    @article = Article.paginate(page: params[:page], per_page: 1)
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(get_params)
    @article.user = current_user
    if @article.save
      flash[:notice] = 'Article created sucessfully'
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @article.update(get_params)
      flash[:notice] = 'Article updated sucessfully'
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def get_params
    params.require(:article).permit(:title, :description, category_ids: [])
  end

  def required_same_user
    if current_user != @article.user && !current_user.admin?
      flash[:alert] = 'You can only edit and delete your own article'
      redirect_to @article
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :admin_required, except: %i[index show]

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Category was successfully created"
      redirect_to @category
    else
      render 'new'
    end
  end

  def index
    @categories = Category.paginate(page: params[:page], per_page: 1)
  end

  def show
    @category = Category.find(params[:id])
    @article = @category.article.paginate(page: params[:page], per_page: 1)
  end

  def edit
   @category = Category.find(params[:id])
  end
  
  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:notice] = "Category name updated succesfully"
      redirect_to @category
    else 
      render category_edit
    end    
   end
  
  private

  def category_params
    params.require(:category).permit(:name)
  end

  def admin_required
    if !(logged_in? && current_user.admin?)
      flash[:alert] = 'Only admin can create the category'
      redirect_to categories_path
    end
  end  
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

# pages controller
class PagesController < ApplicationController
  def home
    redirect_to articles_path if logged_in?
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

# session controller
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user&.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = 'Login is successfull'
      redirect_to user
    else
      flash.now[:alert] = 'You entered wrong credentials'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = 'Logged out'
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

# user controller
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  before_action :required_user, only: %i[edit update destroy]
  before_action :required_same_user, only: %i[edit update destroy]

  def show
    @article = @user.articles.paginate(page: params[:page], per_page: 1)
  end

  def index
    @user = User.paginate(page: params[:page], per_page: 1)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(get_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = 'Welcome to Reactor6'
      redirect_to articles_path
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @user.update(get_params)
      flash[:notice] = 'User updated successfully'
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil if @user == current_user
    flash[:notice] = 'User and all releated article are deleted'
    redirect_to articles_path
  end

  private

  def get_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def required_same_user
    if current_user != @user && !current_user.admin?
      flash[:alert] = 'You logged in with different user'
      redirect_to @user
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# application helper
module ApplicationHelper
  def gravatar_for(user, options = { size: 80 })
    # include MD5 gem, should be part of standard ruby install
    # get the email from URL-parameters or what have you and make lowercase
    email_address = user.email.downcase

    # create the md5 hash
    hash = Digest::MD5.hexdigest(email_address)

    image_size = options[:size]

    # compile URL which can be used in <img src="RIGHT_HERE"...
    image_src = "https://www.gravatar.com/avatar/#{hash}?s=#{image_size}"

    image_tag(image_src, alt: user.username, class: 'rounded shadow mx-auto d-block')
  end
end

app/views/articles/_article.html.erb
<div class="container">
  <% @article.each do |article| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            <% if article.user %>
              by <%= link_to article.user.username, user_path(article.user) %>
            <% end %>
              <% if article.categories.any? %>
                <div class=mt-2><%= render article.categories %></div>
              <% end %>
          </div>
          <div class="card-body">
            <h5 class="card-title"><%= link_to article.title, article_path(article), class: "text-success" %></h5>
            <p class="card-text"><%= truncate(article.description, length: 100) %></p>
            <%= link_to "View", article_path(article), class: "btn btn-outline-success" %>
              <% if logged_in?  && (article.user == current_user || current_user.admin?) %>
                <%= link_to "Edit", edit_article_path(article), class: "btn btn-outline-info" %>
                <%= link_to "Delete", article_path(article), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
              <% end %>
          </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(article.created_at) %> ago, 
            edited <%= time_ago_in_words(article.updated_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/articles/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', obj: @article %>
      <%= form_with(model: @article, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :title, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :title, class: "form-control shadow rounded", placeholder: "Title of article" %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :description, class: "col-2 col-form-label text-light" %>
          <div class="col-10"> 
            <%= f.text_area :description, rows: 10, class: "form-control shadow rounded", placeholder: "Description of article" %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :category, class: "col-2 col-form-label text-light" %>
          <div class="col-10"> 
            <%= f.collection_select(:category_ids, Category.all, :id, :name,
            { prompt: "Make your selection from the list below (can be empty)"}, { multiple: true, size: 3, class: "custom-select shadow rounded" }) %>
          </div>
        </div>

        <div class="form-group row justify-content-center">
          <%= f.submit class: "btn btn-outline-light btn-lg" %>
        </div>
      <% end %>
    </div>
    <div class="mb-3">
      <%= link_to '[ Cancel and return to articles listing ]', articles_path, class: "text-info" %>
    </div>
  </div>
</div>

app/views/articles/edit.html.erb
<div id="page-content">
    <h1 class="text-center mt-4">Edit article</h1>
    <%= render 'form' %>
</div>

app/views/articles/index.html.erb
<div id="page-content">
<h1 class="text-center mt-4">Listing all articles</h1>
    <div class="apple_pagination">
    <div class="page_info">
        <%= page_entries_info @article %>
    </div>
        <%= will_paginate @article, :container => false %>
    </div>
    <%= render @article %>
</div>

app/views/articles/new.html.erb
<div id="page-content">
    <h1 class="text-center mt-4">Create a new article</h1>
    <%= render 'form' %>
</div>

app/views/articles/show.html.erb
<h2 class="text-center mt-4"><%= @article.title %></h2>
<div id="page-content">
  <div class="container">
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            by <%= @article.user.username if @article.user %>
            <%= link_to gravatar_for(@article.user), user_path(@article.user) %>
             
                <% if @article.categories.any? %>
                <div class=mt-2><%= render @article.categories %></div>
                <% end %>
              
          </div>
          <div class="card-body">
            <div class="card-text text-left"><%= simple_format(@article.description) %></div>
              <% if logged_in?  && ( @article.user == current_user || current_user.admin? )%>
                <%= link_to "Edit", edit_article_path(@article), class: "btn btn-outline-info" %>
                <%= link_to "Delete", article_path(@article), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
              <% end %>
          </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(@article.created_at) %> ago, 
            edited <%= time_ago_in_words(@article.updated_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  </div>
  </div>

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), class: "badge badge-pill badge-info mr-1" %>

app/views/categories/_form.html.erb
<%= render '/shared/errors', obj: @category %>
    <%= form_with(model: @category, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
        <div class="form-group row">
                <%= f.label :name, "Cateegory Name", class: "col-2 col-form-label text-light" %>
            <div class="col-10">
                <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "Enter a name" %>
            </div> 
        </div>
    <div class="form-group row justify-content-center">
        <%= f.submit class: "btn btn-outline-light btn-lg" %>
    </div>
    <% end %>
</div>

app/views/categories/edit.html.erb
<div id="page-content">
    <h1 class="text-center mt-4">Create New Category</h1>
        <div class="container">
            <div class="justify-content-center">
                <div class="col=10">
                    <%= render 'form' %>
                </div>
            </div>
        <div id="page-content mb-3", class="text-center">
        <%= link_to '[ Cancel and Return To Category ]', category_path(@category), class:"text-info" %>
        </div>  
</div>

app/views/categories/index.html.erb
<div id="page-content">
        <h1 class="text-center mt-4">Categories</h1>
        <div class="apple_pagination">
        <div class="page_info">
            <%= page_entries_info @category %>
        </div>
            <%= will_paginate @category, :container => false %>
        </div>
        <div class="container">
            <%= @categories.each do |category|%>
                <div class="row justify-content-md-center">
                    <div class="col-4 mt-4">
                        <div class="card text-center shadow mb-5 bg-white rounded">
                                        <div class="card-body">
                                            <h5 class="card-title"><%= link_to category.name, category_path(category), class:"text-success" %></h5>
                                            <p class="card-text"><%= pluralize(category.article.count, "article") %></p> 
                                        </div>
                                <div class="card-footer text-muted">
                                <small> created <%= time_ago_in_words(category.created_at) %>ago
                                edited  <%= time_ago_in_words(category.updated_at) %> ago</smalll>
                            </div>
                        </div>
                    </div>
                </div>
            <% end %>  
        </div>
</div>

<div class="apple_pagination">
        <div class="page_info">
            <%= page_entries_info @category %>
        </div>
            <%= will_paginate @category, :container => false %>
</div>

app/views/categories/new.html.erb
<div id="page-content">
    <h1 class="text-center mt-4">Create New Category</h1>
        <div class="container">
            <div class="justify-content-center">
                <div class="col=10">
                    <%= render 'form' %>
                </div>
            </div>
        <div id="page-content mb-3", class="text-center">
        <%= link_to '[ Return To Article ]', articles_path, class:"text-info" %>
        </div>  
</div>

app/views/categories/show.html.erb
<div id="page-content">
<h1 class="text-center mt-4">Category: <%= @category.name %>'s profile</h1>
        
            <div class="text-center mt-4">
                <% if logged_in? && current_user && current_user.admin %>
                    <%= link_to "Edit your category", edit_category_path(@category), class: "btn btn-outline-info" %>
                <% end %>    
            </div>
        <h3 class="text-center mt-4">Articles</h3>
            <div class="apple_pagination">
                <div class="page_info">
                    <%= page_entries_info @article %>
                    </div>
                        <%= will_paginate @article, :container => false %>
                    </div>
            <div class="container">
    <%= render 'articles/article' %>
</div>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="flex-shrink-0 py-4 bg-dark text-white-50">
<div class="container text-center">
  <small>Copyright &copy; Reactor</small>
</div>
</footer>

app/views/layouts/_messages.html.erb
<% if flash.any? %>
<div class="container">
    <% flash.each do |key,message|%>
        <div class="alert alert-<%= key == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
            <%= message %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <% end %>
    </div>   
 </div>
 <% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "REACTOR", root_path, class: "navbar-brand", id: "logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Bloggers", users_path, class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Articles
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% if logged_in? %>
            <%= link_to "Create new article", new_article_path, class: "dropdown-item" %>
          <% end %>  
          <%= link_to "View articles", articles_path, class: "dropdown-item" %>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Category
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% if logged_in? && current_user.admin? %>
            <%= link_to "Create new category", new_category_path, class: "dropdown-item" %>
          <% end %>  
          <%= link_to "View Categories", categories_path, class: "dropdown-item" %>
        </div>
      </li>
      <% if logged_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= "(Admin)" if current_user.admin %>Profile [<%= current_user.username %>]
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "View your profile", user_path(current_user), class: "dropdown-item" %>
            <%= link_to "Edit your profile", edit_user_path(current_user), class: "dropdown-item" %>
            <%= link_to "Delte profile", user_path(current_user), class: "dropdown-item text-danger", method: :delete, data: {confirm: "Are you sure?" } %>
          </div>
        </li>
        <li class="nav-item">
          <%= link_to 'Logout', logout_path, class: "nav-link", method: :delete %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Log in', login_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign up', signup_path, class: "nav-link" %>
        </li>
      <% end %>
      </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
    

<%= render 'layouts/navigation' %>
<%= render 'layouts/messages' %>
<%= yield %>
<%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container" id="home-container">
  <h1 class="display-6">Reactor</h1>
  <p class="lead">This is an article application. Where user can create - edit and delete article.</p>
  <hr class="my-6">
  <p>Admin can only delete article and other user profile but cannot edit other user profile.</p>
  <%= link_to "Sign Up", signup_path, class:"btn btn-primary btn-success btn-lg" %>
</div>
<div id="page-content">
  </div>

app/views/shared/_errors.html.erb
<% if obj != nil && obj.errors != nil && obj.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from being saved</h4>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/users/_article.html.erb
<div class="container">
  <% @user.article.each do |article| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            <% if article.user %>
              by <%= link_to article.user.username, user_path(article.user) %>
            <% end %>
          </div>
          <div class="card-body">
            <h5 class="card-title"><%= link_to article.title, article_path(article), class: "text-success" %></h5>
            <p class="card-text"><%= truncate(article.description, length: 100) %></p>
            <%= link_to "View", article_path(article), class: "btn btn-outline-success" %>
            <%= link_to "Edit", edit_article_path(article), class: "btn btn-outline-info" %>
            <%= link_to "Delete", article_path(article), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
          </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(article.created_at) %> ago, 
            edited <%= time_ago_in_words(article.updated_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/users/_form.html.erb
<div class="container">
<div class="justify-content-center">
  <div class="col=10">
    <%= render '/shared/errors', obj: @user %>
      <%= form_with(model: @user, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
        <div class="form-group row">
            <%= f.label :username, class: "col-2 col-form-label text-light" %>
              <div class="col-10">
                <%= f.text_field :username, class: "form-control shadow rounded", placeholder: "Username" %>
              </div> 
        </div>

        <div class="form-group row">
            <%= f.label :email, class: "col-2 col-form-label text-light" %>
              <div class="col-10">
                <%= f.text_field :email, class: "form-control shadow rounded", placeholder: "Email" %>
              </div> 
        </div>

        <div class="form-group row">
            <%= f.label :password, class: "col-2 col-form-label text-light" %>
              <div class="col-10">
                <%= f.text_field :password, class: "form-control shadow rounded", placeholder: "Password" %>
              </div> 
        </div>

        <div class="form-group row justify-content-center">
          <%= f.submit ( @user.new_record? ? "Sign Up" : "Update Account"), class: "btn btn-outline-light btn-lg" %>
        </div>

      <% end %>
    </div>
  </div>
</div>
<div id="page-content mb-3", class="text-center">
  <%= link_to '[ Return To Article ]', articles_path, class:"text-info" %>
</div>  

app/views/users/edit.html.erb
<div id="page-content">
    <h1 class="text-center mt-4">Update User</h1>
    <%= render '/users/form' %>
</div>

app/views/users/index.html.erb
<h1 class="text-center mt-4">Reactor</h1>
  <div class="apple_pagination">
      <div class="page_info">
          <%= page_entries_info @user %>
      </div>
          <%= will_paginate @user, :container => false %>
      </div>
  <div class="container">
  <% @user.each do |user| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            <%= link_to user.username, user %>
          </div>
          <div class="card-body">
            <h5 class="card-title">
              <%= link_to gravatar_for(user, size: 150), user %>
            </h5>
            <p class="card-text"><%= pluralize(user.articles.count, "article") %></p>
            <%= link_to "View profile", user, class: "btn btn-outline-success" %>
            <% if logged_in? %>
              <% if logged_in? && user == current_user %>
                <%= link_to "Edit profile", edit_user_path(user), class: "btn btn-outline-info" %>
              <% end %>
              <% if logged_in? && current_user.admin? %>
                <%= link_to "Delete profile", user_path(user), class: "btn btn-outline-info text-danger", method: :delete, data: {confirm: "Are you sure you want to delete profile?"} %>
              <% end %>
            <% end %>  
          </div>
          <div class="card-footer text-muted">
            <small>Joined <%= time_ago_in_words(user.created_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<div id="page-content">
    <h1 class="text-center mt-4">Sign Up</h1>
    <%= render '/users/form' %>
</div>

app/views/users/show.html.erb
<div id="page-content">
    <h1 class="text-center mt-4"><%= @user.username %>'s profile</h1>
        <%= gravatar_for @user, size: 200 %>
            <div class="text-center mt-4">
                <% if logged_in? && @user == current_user %>
                    <%= link_to "Edit your profile", edit_user_path(@user), class: "btn btn-outline-info" %>
                <% end %>    
            </div>
        <h3 class="text-center mt-4">Articles</h3>
            <div class="apple_pagination">
                <div class="page_info">
                    <%= page_entries_info @article %>
                    </div>
                        <%= will_paginate @article, :container => false %>
                    </div>
            <div class="container">
    <%= render 'articles/article' %>
</div>